### ISSUE TITLE
Raise an error if a layout can't be found.

### ISSUE THREAD

**Issue by tomekwojcik** [dynamo/dynamo#45]
Right now, if a layout is not found (either because it's not available in the template format or because the file wasn't found) Dynamo acts as if there was no layout set (i.e. outputs just the rendered template). It'd be cool (at least IMHO) if it raised `Dynamo.TemplateNotFound` just as it does when the template wasn't found.

**Comment by josevalim** [comment]
The problem is that you may have a layout only for some formats, that's why
we don't raise. We could raise, but then we would need a mechanism to
mention if the layout is required or not (which is more complexity).

## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer
