### ISSUE TITLE
deps.compile fails with (ErlangError) erlang error: :eacces on windows

### ISSUE THREAD

**Issue by Sushisource** [dynamo/dynamo#83]
Hi all - not sure if this belongs here or on the elixir tracker so I apologize in advance if it's the wrong place.

Running into this while trying to compile dynamo deps on windows - this applies to dynamo projects generated via **mix dynamo /path/** too.

The output is pretty abrupt:

```
* Compiling mimetypes
** (ErlangError) erlang error: :eacces
```

If I were to take a guess it'd be this line: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/deps.compile.ex#L62

I would love to jump in and fix it myself - but the current version of cygwin make has a bug that causes it to crash on elixir's makefile! I'll have to see about contributing from my mac.

Love the language!

**Comment by josevalim** [comment]
Hello @Sushisource! Unix systems are definitely more recommended for building Elixir and working with the Erlang VM. In any case, we should take a look at the issue you have found. Btw, do you have a stacktrace with the error?

We are glad to hear you are enjoying the language!

**Comment by Sushisource** [comment]
Unfortunately there doesn't seem to be a stacktrace - that's all the output. If I can pass some flags / set an env variable or something to make it produce one I'd be happy to do that.

I realize I'm asking for punishment doing this stuff on windows :). I was thinking it wouldn't be too hard to create a cmake file or some other cross-platform equivalent for elixir. That's a separate topic but let me know if you're interested.

**Comment by josevalim** [comment]
According to erlang docs, `eacces` is caused by file access permissions. I am not sure if this helps though?

And yes, I am interested on making compilation easier on Windows and I would love to hear the alternatives available! Yesterday we just started a discussion on the mailing list to help us clean up some Windows issues.

Currently, it seems some people are being able to compile Elixir on Windows using MinGW. There are also other factors to consider, like which compilation mode plays better with the Elixir shell (IEx).

**Comment by Sushisource** [comment]
I had read that about `eaccess` in the docs as well, even tried just giving blanket permissions to everyone to the directory, no luck.

I'll join the mailing list and propose some ideas for windows-compatible build scripts.
